### PR TITLE
Add merge overlaps function

### PR DESCRIPTION
**Pull request by lisawink**
Have added a function merge_overlaps in overlap.py which merges any overlapping polygons sharing an overlap area larger than 'overlap_limit'. Overlapping polygons smaller than 'merge_limit' are always merged, no matter the overlap area. Tests are included in test_overlap.py and examples in overlaps.ipynb

### CODE REVIEW

**Comment by martinfleis** [comment]
I am not sure if that last example in the notebook is desired behaviour. It seems weird to see those two large polygons merged together.

**Comment by lisawink** [comment]
I agree it is weird, but because the polygons are merged in order, when the smaller polygon is merged to one of the bigger polygons, this now overlaps with the other big polygon, and so it is all merged together. Any other solution would require trimming, which could be done first with trim_overlaps, and then with merge_overlaps or merge_touching. I think it really depends on the use-case.

**Comment by martinfleis** [comment]
That's probably fair.

**Comment by sjsrey** [comment]
I had the same initial reaction as @martinfleis, but then, thinking through the logic, I agree with @lisawink that the results make sense.

This brings up a more general question of how the sequence of operations may result in different outcomes - I think this is a really interesting problem. I think the role of the package would be to handle individual operations correctly and provide the user with the ability to combine them in sequences that make sense for different use cases.

**Comment by martinfleis** [comment]
> This brings up a more general question of how the sequence of operations may result in different outcomes - I think this is a really interesting problem. I think the role of the package would be to handle individual operations correctly and provide the user with the ability to combine them in sequences that make sense for different use cases.

Fully agree. In our case of building footprints, @lisawink spent some time figuring out the correct order of operations and it does indeed make a difference. But that will be case specific, so I would not impose any sequence within `geoplanar`.

**Pull request merged**
