### PR TITLE
MAINT: update infrastructure

### PR DESCRIPTION
**Pull request by martinfleis**
Mostly mirroring the state of infrastructure used in pysal.

- move to pyproject.toml
- move to setuptools_scm
- move to ruff
- format using ruff
- release action

@sjsrey can you add a `PYPI_PASSWORD` secret using PyPI token able to make a geoplanar release? Or you can add me on PyPI and I can take care of that myself.

### CODE REVIEW

**Comment by martinfleis** [comment]
We probably also should install the [Codecov GitHub app](https://github.com/apps/codecov/installations/select_target) to fix it.

**Comment by martinfleis** [comment]
@sjsrey I actually don't have enough rights to add repository secrets here...

**Comment by sjsrey** [comment]
> @sjsrey I actually don't have enough rights to add repository secrets here...

I don't see how to change your rights here.

I added the PYPI_PASSWORD secret - will that be enough for the release?

**Comment by martinfleis** [comment]
> I don't see how to change your rights here.

I don't think it is possible under personal account. 

> I added the PYPI_PASSWORD secret - will that be enough for the release?

Should be. I'll give it a go with a patch release containing the compatibility updates.

**Comment by martinfleis** [comment]
All good - https://pypi.org/project/geoplanar/0.3.1/. https://github.com/sjsrey/geoplanar/releases/tag/v0.3.1

**Pull request merged**
